package com.devtrack.calendar.entity;

/**
 * MANUAL — created directly by the user via the API. STUDY_PLAN — auto-generated by
 * StudyPlanEventListener; never editable via the client-facing API (EventService rejects
 * PATCH/DELETE on these — see its docblock). JOB_APPLICATION is added in Phase 3 once that module
 * exists.
 */
public enum EventSource {
  MANUAL,
  STUDY_PLAN
}
