package com.devtrack.calendar.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.devtrack.calendar.dto.request.CreateEventRequest;
import com.devtrack.calendar.dto.request.UpdateEventRequest;
import com.devtrack.calendar.entity.Event;
import com.devtrack.calendar.entity.EventSource;
import com.devtrack.calendar.repository.EventRepository;
import com.devtrack.common.exception.ResourceNotFoundException;
import com.devtrack.common.exception.ValidationException;
import com.devtrack.common.security.OwnershipGuard;
import java.time.Instant;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class EventServiceTest {

  private EventRepository eventRepository;
  private EventService eventService;

  private final UUID ownerId = UUID.randomUUID();
  private final UUID otherUserId = UUID.randomUUID();

  @BeforeEach
  void setUp() {
    eventRepository = mock(EventRepository.class);
    eventService = new EventService(eventRepository, new OwnershipGuard());
  }

  @Test
  void createEvent_alwaysCreatesManualSource() {
    when(eventRepository.save(any(Event.class))).thenAnswer(inv -> inv.getArgument(0));

    var response =
        eventService.createEvent(
            ownerId, new CreateEventRequest("Standup", null, Instant.now(), null));

    assertThat(response.source()).isEqualTo("MANUAL");
  }

  @Test
  void updateEvent_forNonOwner_throwsNotFound() {
    Event event = manualEvent(ownerId);
    when(eventRepository.findById(event.getId())).thenReturn(Optional.of(event));

    assertThatThrownBy(
            () ->
                eventService.updateEvent(
                    event.getId(), otherUserId, new UpdateEventRequest("x", null, null, null)))
        .isInstanceOf(ResourceNotFoundException.class);
    verify(eventRepository, never()).save(any());
  }

  /** The rule from 06_API_Specification.md §4.2 — the one this whole slice exists to enforce. */
  @Test
  void updateEvent_onAutoGeneratedEvent_isRejected() {
    Event event = manualEvent(ownerId);
    event.setSource(EventSource.STUDY_PLAN);
    event.setSourceId(UUID.randomUUID());
    when(eventRepository.findById(event.getId())).thenReturn(Optional.of(event));

    assertThatThrownBy(
            () ->
                eventService.updateEvent(
                    event.getId(), ownerId, new UpdateEventRequest("x", null, null, null)))
        .isInstanceOf(ValidationException.class);
    verify(eventRepository, never()).save(any());
  }

  @Test
  void deleteEvent_onAutoGeneratedEvent_isRejected() {
    Event event = manualEvent(ownerId);
    event.setSource(EventSource.STUDY_PLAN);
    when(eventRepository.findById(event.getId())).thenReturn(Optional.of(event));

    assertThatThrownBy(() -> eventService.deleteEvent(event.getId(), ownerId))
        .isInstanceOf(ValidationException.class);
  }

  @Test
  void upsertFromSource_withNoExistingEvent_createsNewOne() {
    UUID sourceId = UUID.randomUUID();
    when(eventRepository.findBySourceAndSourceId(EventSource.STUDY_PLAN, sourceId))
        .thenReturn(Optional.empty());
    when(eventRepository.save(any(Event.class))).thenAnswer(inv -> inv.getArgument(0));

    eventService.upsertFromSource(
        ownerId, EventSource.STUDY_PLAN, sourceId, "Finish React module", Instant.now());

    verify(eventRepository).save(any(Event.class));
  }

  /**
   * The behavior 05_Database_Architecture.md §10 specifically calls for — a repeat event updates,
   * never duplicates.
   */
  @Test
  void upsertFromSource_withExistingEvent_updatesInPlaceRatherThanDuplicating() {
    UUID sourceId = UUID.randomUUID();
    Event existing = manualEvent(ownerId);
    existing.setSource(EventSource.STUDY_PLAN);
    existing.setSourceId(sourceId);
    existing.setTitle("Old title");
    when(eventRepository.findBySourceAndSourceId(EventSource.STUDY_PLAN, sourceId))
        .thenReturn(Optional.of(existing));
    when(eventRepository.save(any(Event.class))).thenAnswer(inv -> inv.getArgument(0));

    eventService.upsertFromSource(
        ownerId, EventSource.STUDY_PLAN, sourceId, "New title", Instant.now());

    assertThat(existing.getTitle()).isEqualTo("New title");
    assertThat(existing.getId()).isNotNull(); // same row, not a fresh one
  }

  private Event manualEvent(UUID ownerId) {
    Event event = new Event();
    event.setId(UUID.randomUUID());
    event.setUserId(ownerId);
    event.setTitle("An event");
    event.setStartAt(Instant.now());
    event.setSource(EventSource.MANUAL);
    return event;
  }
}
